Additional SSL Improvements
grahamwetzler/smart-meter-texas pull request #124
Opened 2021-08-14 07:11 UTC by meyerrj

Attempting to work around SSL certificate chain issues with the smartmetertexas.com website.

This patch is a work-around that uses the currently known SSL certificate's fingerprint for smartmetertexas.com which will expire in October. 

More information on the findings can be found in this PR:  https://github.com/home-assistant/core/pull/54493

2021-08-14 17:13 UTC, meyerrj commented
I added some logic that will test the SSL connection and return the currently known fingerprint, and then compare with the hard coded value before proceeding. This should allow for the code to respond to a new certificate if/when it is replaced before its expiration date.

2021-08-21 02:38 UTC, meyerrj commented
@grahamwetzler  Would you be willing to review these changes and let me know if everything looks good on your end?

If everything is good, I can update the Home Assistant implementation to use the SSL logic in the examples with a version bump. :)

2021-08-21 14:50 UTC, grahamwetzler requested changes
Please see comments. Also please run `black` for consistent formatting. Thanks for your hard work!

2021-08-21 14:50 UTC, grahamwetzler commented on examples/get_meter_reading.py
> +
Can this be moved to another file and imported here? I’d like to keep the examples simple if possible.

2021-08-21 14:50 UTC, grahamwetzler commented on examples/get_meters.py
> +
Same as other example file

2021-08-21 14:50 UTC, grahamwetzler commented on examples/get_meter_reading.py
> +import urllib
Please run `isort` to format the imports.

2021-08-21 14:50 UTC, grahamwetzler commented on examples/get_meter_reading.py
> +    caiKey = 'CA Issuers - URI:'
Please use `snake_case` for variables.

2021-08-21 14:50 UTC, grahamwetzler commented on smart_meter_texas/__init__.py
> +from aiohttp.http import RESPONSES
This doesn’t seem to be needed

2021-08-21 17:46 UTC, meyerrj commented
@grahamwetzler I believe I've addressed the change requests in the latest commit. Please let me know if it looks good now. 😀

2021-08-21 18:38 UTC, grahamwetzler approved these changes
Looks good. Thanks!

2021-08-21 18:40 UTC, merged